# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20190618_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentbug',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentfeature',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
