# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20190621_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='resolved_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='implemented_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(blank=True, choices=[('TODO', 'todo'), ('DOING', 'doing'), ('DONE', 'done')], default='TODO', max_length=7),
        ),
    ]
