# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20190621_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='resolved_date',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='implemented_date',
        ),
    ]
