# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190708_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='avatar/'),
        ),
    ]
